# -*- coding: utf-8 -*-
"""Practical 3 dsbda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17iqqImS7uZkFqy7pPTemGUuR6c5AYGJX
"""

import pandas as pd

d = pd.read_csv('/content/Iris.csv')

setosa = d['Species'] == 'Iris-setosa'

print(d[setosa].describe())

setosa = d['Species'] == 'Iris-versicolor'

print(d[setosa].describe())

setosa = d['Species'] == 'Iris-virginica'

print(d[setosa].describe())

d.groupby(["Species"])["SepalLengthCm"].mean()

d.groupby(["Species"])["SepalLengthCm"].std()

d.groupby(["Species"])["SepalLengthCm"].describe()

d.groupby(["Species"])["SepalLengthCm"].quantile(q = 0.75)

d.groupby(["Species"])["SepalLengthCm"].quantile(q = 0.50)

a = d.groupby(["Species"])["SepalLengthCm"].median()

print(a)

b = d.groupby(["Species"])["SepalLengthCm"].mean()

print(b)

list[a,b]

