# -*- coding: utf-8 -*-
"""Practical 10 Dsbda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jqW9zkH5jdNIHUaCa4Ux3LRGKnvpGj4f
"""

import pandas as pd

import numpy as np

df=pd.read_csv('IRIS.csv')

df.describe()

df.head()

print(df.columns)

df.info()

df.dtypes

df.hist()

import matplotlib.pyplot as plt

import seaborn as sns

sns.histplot(df["sepal_length"])

fig,axes = plt.subplots(2,2, figsize=(16,8))
axes[0,0].set_title("Distributio of first colums")
axes[0,0].hist(df["sepal_length"]);

axes[0,1].set_title("Distributio of Second colums")
axes[0,1].hist(df["sepal_width"]);

axes[1,0].set_title("Distributio of third colums")
axes[1,0].hist(df["petal_length"]);

axes[1,1].set_title("Distributio of Fourth colums")
axes[1,1].hist(df["petal_width"]);

data_to_plot = [df["sepal_length"],df["sepal_width"],df["petal_length"], df["petal_width"]]

fig = plt.figure(1, figsize = (12,8))
ax = fig.add_subplot(111)
bp = ax.boxplot(data_to_plot);

sns.boxplot(df["sepal_width"])

print(np.where(df["sepal_width"]>4.0))



