# -*- coding: utf-8 -*-
"""Practical 9 Dsbda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZZ_n1Y7OZySbenwXcKmg9i_-WZUF-hmm
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

dataset = sns.load_dataset('titanic')

sns.barplot(x = 'sex', y = 'age', data = dataset)

sns.boxplot(x = 'sex', y = 'age', data = dataset)

sns.boxplot(x = 'sex', y = 'age', data = dataset, hue = 'survived')

