# -*- coding: utf-8 -*-
"""Practical 2 dsbda

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13ciy9gueF26kCP45C_1RS4-f-p_Jy12z
"""

import pandas as pd

df = pd.read_csv('/content/academic (1).csv')

df.head()

df

df.isnull

df.isnull()

df.isnull().sum()

df['raisedhands'] = df['raisedhands'].fillna(df['raisedhands'].mean())

df['gender'] = df['gender'].fillna(df['gender'].mode()[0])

df.isnull().sum()

import seaborn as sns

sns.boxplot(df)

