# -*- coding: utf-8 -*-
"""Practical 6 Dsabda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18WROERaZ2vGf9BgKNDYg6xO-VxhWRmiY
"""

import numpy as np

import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import pandas as pd
import seaborn as sns

data = pd.read_csv('/content/Iris.csv')

data.head()

X = data.iloc[:,:4].values

Y = data['Species'].values

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.20, random_state = 8)

from sklearn.naive_bayes import GaussianNB
nvclassifier = GaussianNB()
nvclassifier.fit(X_train, Y_train)

Y_pred = nvclassifier.predict(X_test)

print(Y_pred)

Y_compare = np.vstack((Y_test, Y_pred)).T

Y_compare[:5,:]

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, Y_pred)

sns.heatmap(cm, annot = True)
plt.xlabel("Predicted Label")
plt.ylabel("Actual Label")
plt.title("Confussion MAtrix")
plt.show()
print(cm)

from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
results = confusion_matrix(Y_test, Y_pred)

print ("Confusion MAtrix : ")
print(results)
print ("Accuracy Score : ", accuracy_score(Y_test, Y_pred))
print("Classification Report :")
print(classification_report(Y_test, Y_pred))

Accuracy = accuracy_score (Y_test, Y_pred)
print(Accuracy)
Error_rate = 1-Accuracy
print(Error_rate)

