# -*- coding: utf-8 -*-
"""Practical 1 Dsbda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_lGctDw2IDaQACaAYWYyMjHapja9b3EG
"""

import pandas as pd

df = pd.read_csv('/academic.csv')
df.head()



df.isnull()

df.isnull().sum()

df.notnull()

df.describe()

df.dtypes

df.ndim

df['raisedhands'] = df['raisedhands'].fillna(df['raisedhands'].mean())

df.isnull().sum()

df['raisedhands'].astype(int)

df.dtypes

df['raisedhands'] = df['raisedhands'].astype(int)

df.dtypes

df

df_encoding= pd.get_dummies(df,columns = ['gender'])
df_encoding

