# -*- coding: utf-8 -*-
"""Practical 8 Dsbda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kc67-FObVzip13QnaUtmY2SmkU7Jl6WV
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn

import seaborn as sns
dataset = sns.load_dataset('titanic')

dataset.head()

sns.barplot(x = 'sex', y = 'age', data = dataset)

sns.catplot(x = 'sex', hue = 'survived',
kind = 'count', data = dataset)

sns.histplot(data = dataset, x='fare')

sns.histplot(data = dataset, x ='fare', binwidth = 30)

