# -*- coding: utf-8 -*-
"""Practical 5 Dsbda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GkHuJejinYlOxwbKi-S01SDLNcGBDzWs
"""

import pandas as pn
df = pn.read_csv('/content/Social_Network_Ads.csv')

df.head()

def gender_encoder(value):
    if (value == "Male"):
        return 1
    elif (value == "Female"):
        return 0
    else:
        return -1

df["Gender"] = df["Gender"].apply(gender_encoder)

df.head()

x = df[["User ID",	"Gender",	"Age", "EstimatedSalary"]]
y = df["Purchased"]

from sklearn.preprocessing import StandardScaler

scalar = StandardScaler()

x = scalar.fit_transform(x)

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test =  train_test_split(x, y, test_size = 0.20, random_state = 42)

x_train

y_test

from sklearn.linear_model import LogisticRegression

Logistic = LogisticRegression()

Logistic.fit(x_train, y_train)

y_pred = Logistic.predict(x_test)

y_pred

y_test

from sklearn.metrics import confusion_matrix
cn = confusion_matrix(y_test, y_pred)
print(cn)

import seaborn as sns

sns.heatmap(cn, annot = True)

from sklearn.metrics import accuracy_score
print(accuracy_score(y_pred, y_test))

error_rate = 1-accuracy_score(y_pred, y_test)
error_rate

from sklearn.metrics import classification_report

print(classification_report(y_pred, y_test) )

